In [ ]:
import numpy as np


print(np.__version__)

1.21.6


In [ ]:
import numpy as np
 
 
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])
 
B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
 
C = np.array([[True, False, False],
              [True, True, True]])
 
D = np.array([0.1, 0.3])
 
for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.all(array)}')


A: True
B: False
C: False
D: True


In [ ]:
import numpy as np
 
 
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])
 
B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
 
C = np.array([[True, False, False],
              [True, True, True]])
 
for name, array in zip(list('ABC'), [A, B, C]):
    print(f'{name}: {np.all(array, axis=1)}')

A: [ True  True]
B: [ True False]
C: [False  True]


In [ ]:
import numpy as np
 
 
A = np.array([[0, 0, 0],
              [0, 0, 0]])
 
B = np.array([[0, 0, 0],
              [0, 1, 0]])
 
C = np.array([[False, False, False],
              [True, False, False]])
 
D = np.array([[0.1, 0.0]])
 
for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.any(array)}')

A: False
B: True
C: True
D: True


In [ ]:
import numpy as np
 
 
A = np.array([[0, 0, 0],
              [0, 0, 0]])
 
B = np.array([[0, 0, 0],
              [0, 1, 0]])
 
C = np.array([[False, False, False],
              [True, False, False]])
 
D = np.array([[0.1, 0.0]])
 
for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.any(array, axis=0)}')

A: [False False False]
B: [False  True False]
C: [ True False False]
D: [ True False]


In [ ]:
import numpy as np
 
 
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
 
print(np.isnan(A))

[[False False False  True]
 [False  True False False]]


In [ ]:
import numpy as np
 
 
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])
 
print(np.allclose(A, B))

True


In [ ]:
import numpy as np
 
 
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])
 
print(A == B)

[False False  True]


In [ ]:
import numpy as np
 
 
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])
 
print(np.equal(A, B))

[False False  True]


In [ ]:
import numpy as np
 
 
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])
 
print(A > B)

[ True False False False]


In [ ]:
import numpy as np
 
 
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])
 
print(np.greater(A, B))

[ True False False False]


In [ ]:
import numpy as np
 
 
print(np.zeros(shape=(4, 4), dtype='int'))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
import numpy as np
 
 
print(np.ones(shape=(10, 10), dtype='float') * 255)

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]


In [ ]:
import numpy as np
 
 
print(np.full(shape=(10, 10), fill_value=255, dtype='float'))

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]


In [ ]:
import numpy as np
 
 
print(np.arange(10, 100))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [ ]:
import numpy as np
 
 
print(np.arange(10, 100).reshape(-1, 10)) 


[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
import numpy as np
 
 
print(np.arange(10, 100).reshape(9, 10))


[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
import numpy as np
 
 
print(np.arange(10, 100).reshape(9, -1))

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
import numpy as np
 
 
print(np.eye(N=6, dtype='int'))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [ ]:
import numpy as np
 
 
np.random.seed(10)
print(np.random.rand(30))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]


In [ ]:
import numpy as np
 
 
np.random.seed(20)
print(np.random.randn(10, 4))

[[ 0.88389311  0.19586502  0.35753652 -2.34326191]
 [-1.08483259  0.55969629  0.93946935 -0.97848104]
 [ 0.50309684  0.40641447  0.32346101 -0.49341088]
 [-0.79201679 -0.84236793 -1.27950266  0.24571517]
 [-0.0441948   1.56763255  1.05110868  0.40636843]
 [-0.1686461  -3.18970279  1.12013226  1.33277821]
 [-0.24333877 -0.13003071 -0.10901737  1.55618644]
 [ 0.12877835 -2.06694872 -0.88549315 -1.10457948]
 [ 0.93286635  2.059838   -0.93493796 -1.61299022]
 [ 0.52706972 -1.55110074  0.32961334 -1.13652654]]


In [ ]:
import numpy as np
 
 
np.random.seed(30)
 
sigma = np.sqrt(5)
mu = 100
 
print(sigma * np.random.randn(10, 4) + mu)

[[ 97.17349231 103.41650023  97.82942436 101.05220329]
 [ 99.7748353  100.67930221  96.14063068 103.544381  ]
 [100.30029631  97.52499594 103.52901961 100.24037271]
 [ 98.29153712  98.2666258  103.09437633 101.70027274]
 [ 99.36127721 101.20382627  95.34026547 102.09694365]
 [ 99.98708001  98.95468525  99.05410904 102.38025432]
 [ 93.50787269 103.61547679 103.18753701  98.51356237]
 [102.20256689  96.19764407  97.54000366  97.05813038]
 [101.81233513  97.66380453  98.45883627  98.09317768]
 [102.48979932  95.70413391  98.43161651 101.89861815]]


In [ ]:
import numpy as np
 
 
A = np.array([[1, 4, 3],
              [5, 2, 6]])
 
for i in np.nditer(A):
    print(i)

1
4
3
5
2
6


In [ ]:
import numpy as np
 
 
print(np.linspace(start=0, stop=1, num=11))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [ ]:
import numpy as np
 
 
np.random.seed(42)
print(np.random.choice(range(1, 50), size=6, replace=False))

[14 46 48 45 18 28]


In [ ]:
import numpy as np
 
 
print(np.diag(np.arange(6)))

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


In [ ]:
import numpy as np
 
 
A = np.arange(12).reshape(-1, 4)
np.save('array.npy', A)
 
B = np.load('array.npy')
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
import numpy as np
 
 
A = np.arange(12, dtype='int').reshape(-1, 4)
np.savetxt(fname='array.txt', X=A, fmt='%0.2f')
 
B = np.loadtxt('array.txt')
print(B)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [ ]:
import numpy as np
 
 
A = np.arange(12, dtype='int').reshape(-1, 4)
print(A.tolist())

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


In [ ]:
import numpy as np
 
 
A = np.arange(12, dtype='int').reshape(-1, 4)
print(A[::-1])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [ ]:
import numpy as np
 
 
A = np.ones(shape=(4, 4))
print(np.pad(A, pad_width=1, constant_values=0))

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np
 
 
A = np.zeros(shape=(6, 6), dtype='int')
A[::2, ::2] = 10
A[1::2, ::2] = 5
print(A)

[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]


In [ ]:
import numpy as np
 
 
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
 
print(np.append(A, B, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]


In [ ]:
import numpy as np
 
 
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])
 
print(np.intersect1d(A, B))

[0 2 3]


In [ ]:
import numpy as np
 
 
np.random.seed(10)
A = np.random.randint(low=1, high=10, size=(3, 5))
print(np.unique(A))

[1 2 4 5 7 9]


In [ ]:
import numpy as np
 
 
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
 
print(np.argmax(A, axis=1))

[0 2 1]


In [ ]:
import numpy as np
 
 
A = np.array([[1, 1, 1], [2, 1, 5], [1, -1, -1]])
B = np.array([[1], [0], [0]])
X = np.dot(np.linalg.inv(A), B)
x = X[0][0]
y = X[1][0]
z = X[2][0]
print(f'x = {x:.2f}\ny = {y:.2f}\nz = {z:.2f}')

x = 0.50
y = 0.88
z = -0.38


In [ ]:
import numpy as np
 
 
A = np.array([[5, -3], [1, -2]])
B = np.array([[21], [7]])
X = np.dot(np.linalg.inv(A), B)
x = X[0][0]
y = X[1][0]
print(f'x = {x:.2f}\ny = {y:.2f}')

x = 3.00
y = -2.00


In [ ]:
import numpy as np
 
 
np.set_printoptions(suppress=True)
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5],
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5],
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])
 
flag = playway_values[:, [0]] < playway_values[:, [3]]
flag = flag.astype(int)
playway_values = np.concatenate((playway_values, flag), axis=1)
print(playway_values)

[[   305.     324.5    283.5    310.   64081.      41.       1. ]
 [   325.5    340.5    320.     340.5  55496.      20.5      1. ]
 [   324.     340.5    315.     330.   36152.      25.5      1. ]
 [   344.     344.     310.     315.   35992.      34.       0. ]
 [   306.5    307.     291.     305.   32539.      16.       0. ]
 [   274.     291.     250.     258.   79402.      41.       0. ]
 [   278.     284.5    256.     264.   35700.      28.5      0. ]
 [   270.     270.     238.5    245.   60445.      31.5      0. ]
 [   218.     228.     196.     197.   94031.      32.       0. ]
 [   210.     229.     198.8    211.  100412.      30.2      1. ]
 [   205.     248.     197.8    240.5  50659.      50.2      1. ]
 [   245.     269.     232.5    264.   99480.      36.5      1. ]
 [   264.     280.     251.     270.   70136.      29.       1. ]
 [   267.     280.     267.     279.5  30732.      13.       1. ]
 [   297.5    307.     280.     280.5  43426.      27.       0. ]
 [   274. 

In [ ]:
import numpy as np
 
 
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
 
print(np.sort(A))
print(np.sort(A, axis=0))

[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]
[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]


In [ ]:
import numpy as np
 
 
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
 
print(A[A > 8])

[ 9.99  9.99 14.99]


In [ ]:
import numpy as np
 
 
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
 
print(np.where(A > 10.0, 10.0, A))

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]


In [ ]:
import numpy as np
 
 
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
 
print(np.ravel(A))

[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]
